spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/filestorage
  mongodb:
    auto-index-creation: true

storage:
  endpoint: http://localhost:9000
  accessKey: minioadmin
  secretKey: minioadmin
  bucket: files
  secure: false

server:
  port: 8080
