spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/filestorage
      auto-index-creation: false
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

server:
  port: 8080

storage:
  provider: s3
  endpoint: http://localhost:9000
  accessKey: minioadmin
  secretKey: minioadmin
  bucket: filestorage
  secure: false

app:
  pagination:
    default-size: 20
    max-size: 100

management:
  endpoints:
    web:
      exposure:
        include: health,info,env,configprops,beans
  endpoint:
    health:
      show-details: ALWAYS
    env:
      show-values: ALWAYS
    configprops:
      show-values: ALWAYS
    beans:
      enabled: true