spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
      - org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration
  main:
    allow-bean-definition-overriding: true

storage:
  endpoint: http://localhost:9000
  accessKey: test
  secretKey: test
  bucket: test
  secure: false
