spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/filestorage
      auto-index-creation: false
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

server:
  port: 8080

storage:
  provider: s3
  endpoint: http://localhost:9000
  accessKey: minio
  secretKey: minio123
  bucket: filestorage
  secure: false

app:
  pagination:
    default-size: 20
    max-size: 100
