services:
  mongo:
    image: mongo:7
    ports: ["27017:27017"]
    volumes: ["mongo_data:/data/db"]

  minio:
    image: minio/minio:RELEASE.2025-01-11T00-00-00Z.fips
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes: ["minio_data:/data"]

  app:
    build:
      context: ..
      dockerfile: Dockerfile
    depends_on: [mongo, minio]
    environment:
      - APP_PORT=8080
      - MONGO_URI=mongodb://mongo:27017/filestorage
      - S3_ENDPOINT=http://minio:9000
      - S3_ACCESS_KEY=minioadmin
      - S3_SECRET_KEY=minioadmin
      - S3_BUCKET=files
      - S3_REGION=us-east-1
      - S3_SECURE=false
    ports: ["8080:8080"]
    deploy:
      resources:
        limits:
          memory: 1g

volumes:
  mongo_data:
  minio_data:

